name: React Build and push to build branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Git Set Config
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_USERNAME: ${{ secrets.MY_USERNAME }}
        run: |
            # git remote set-url origin git@github.com:deepak6797/reactcicd.git
            git config --global user.email "$MY_EMAIL"
            git config --global user.name "$MY_USERNAME"
            git config --list
    
      - name: React Build Stage
        run: |
          rm -rf node_modules
          rm -rf build
          npm install
          npm run build
        
      - name: Set key for git
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
    
      - name: Push to build branch
        env:
          REPO_URL: ${{ secrets.REPO_URL }}
        run: |
            cd build
            git init
            git remote add origin $REPO_URL
            git checkout -b build
            git add .
            git commit -m "build file"
            git push -u origin build
    
      - name: Clean up SSH key
        if: always()
        run: rm -f ~/.ssh/id_rsa