name: React Build and push to build branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Git Push
        run: |
            git remote set-url origin git@github.com:deepak6797/reactcicd.git

      - name: List files in directory
        run: |
          rm -rf node_modules
          rm -rf build
          npm install
          npm run build
          ls -la
          git checkout -b build
          git add build
          git commit -m "build file"
          git push -u origin build