name: React Build and push to build branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
    
      - name: React Build Stage
        run: |
          rm -rf node_modules
          rm -rf build
          npm install
          npm run build
    
      - name: Set up SSH key and whitelist EC2 IP address
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan ${{ secrets.AWS_IP }} >> ~/.ssh/known_hosts
        
      - name: Copy file to server
        env:
            AWS_IP: ${{ secrets.AWS_IP }}
            AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
        run: |
            rsync -ahPz build/* $AWS_USERNAME@$AWS_IP:/home/ubuntu/reactjsapp
            rsync -ahPz run.sh $AWS_USERNAME@$AWS_IP:/home/ubuntu/reactjsapp

      - name: Copy file to server
        env:
            AWS_IP: ${{ secrets.AWS_IP }}
            AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
        run: |
            ssh -o StrictHostKeyChecking=no $AWS_USERNAME@$AWS_IP "chmod +x /home/ubuntu/reactjsapp/run.sh && /home/ubuntu/reactjsapp/run.sh"


      - name: Clean up SSH key
        if: always()
        run: rm -f ~/.ssh/id_rsa